### ISSUE TITLE
给抄作业的人看的（～.～）

### ISSUE THREAD

**Issue by KureiSersen** [lrx0014/ExamSys#3]
兄弟，你那个Login.php 第三行echo少了个分号，两个SQL语句 数据库都应该是小写

**Comment by lrx0014** [comment]
@KureiSersen 
第三行的echo是多余的，我也忘了为啥要写它 :(
MySQL当时其实是开启了忽略大小写的设置，我可能会改掉

ps. 这个项目已经年代久远，不会再维护了
这个项目几乎没有使用php框架、实现简单粗暴，适合本科的同学参考参考，作业还是要自己写 ;)

**Comment by chinyifei** [comment]
确实是有参考价值,原生的可以练练手再说!

**Comment by lrx0014** [comment]
已修复大部分问题
